name: Publication WordPress

on:
  push:
    branches:
      - main  # Le flux de travail sera déclenché lors de chaque push vers la branche main

jobs:
  publish_to_wordpress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Publish to WordPress
        run: ./publish-to-wordpress.sh
        env:
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          # Ajoutez d'autres secrets nécessaires ici
